# Generated by Django 3.2.5 on 2021-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0002_flight_hotel_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_no',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='flight',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airport_from',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='flight',
            name='airport_to',
            field=models.CharField(default='', max_length=3),
        ),
    ]
