# Generated by Django 3.2.5 on 2021-07-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripplanner', '0003_auto_20210714_2134'),
        ('tripplanner', '0003_auto_20210715_1635'),
    ]

    operations = [
    ]
